//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeReading.View.HistoryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HistoryService.ICodeReadingService")]
    public interface ICodeReadingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeReadingService/Initialize", ReplyAction="http://tempuri.org/ICodeReadingService/InitializeResponse")]
        CodeReading.Entity.InitializeResult Initialize(CodeReading.Entity.LoginInfo loginInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeReadingService/Initialize", ReplyAction="http://tempuri.org/ICodeReadingService/InitializeResponse")]
        System.Threading.Tasks.Task<CodeReading.Entity.InitializeResult> InitializeAsync(CodeReading.Entity.LoginInfo loginInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeReadingService/Search", ReplyAction="http://tempuri.org/ICodeReadingService/SearchResponse")]
        CodeReading.Entity.SearchResult Search(CodeReading.Entity.SearchConditions searchConditions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeReadingService/Search", ReplyAction="http://tempuri.org/ICodeReadingService/SearchResponse")]
        System.Threading.Tasks.Task<CodeReading.Entity.SearchResult> SearchAsync(CodeReading.Entity.SearchConditions searchConditions);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICodeReadingServiceChannel : CodeReading.View.HistoryService.ICodeReadingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CodeReadingServiceClient : System.ServiceModel.ClientBase<CodeReading.View.HistoryService.ICodeReadingService>, CodeReading.View.HistoryService.ICodeReadingService {
        
        public CodeReadingServiceClient() {
        }
        
        public CodeReadingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CodeReadingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodeReadingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodeReadingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CodeReading.Entity.InitializeResult Initialize(CodeReading.Entity.LoginInfo loginInfo) {
            return base.Channel.Initialize(loginInfo);
        }
        
        public System.Threading.Tasks.Task<CodeReading.Entity.InitializeResult> InitializeAsync(CodeReading.Entity.LoginInfo loginInfo) {
            return base.Channel.InitializeAsync(loginInfo);
        }
        
        public CodeReading.Entity.SearchResult Search(CodeReading.Entity.SearchConditions searchConditions) {
            return base.Channel.Search(searchConditions);
        }
        
        public System.Threading.Tasks.Task<CodeReading.Entity.SearchResult> SearchAsync(CodeReading.Entity.SearchConditions searchConditions) {
            return base.Channel.SearchAsync(searchConditions);
        }
    }
}
