//
// File generated by HDevelop for HALCON/.NET (C#) Version 18.11.1.1
// Non-ASCII strings in this file are encoded in UTF-8.
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
//


using System;
using CodeReading.Entity.MainForm;
using HalconDotNet;

public partial class HDevelopExport
{
  public void image_prog_Null(HObject ho_Image, HTuple rtaHalconWin, HTuple hv_ExpDefaultWinHandle)
  {
    // Stack for temporary objects 
    HObject[] OTemp = new HObject[20];

    // Local iconic variables 

    HObject ho_ImageOut=null, ho_InfoModelContours;
    HObject ho_SignModelContours, ho_SymbolRegions, ho_ROI_OCR_01_0;
    HObject ho_EDGE, ho_ObjectSelected=null, ho_InfoTransContours;
    HObject ho_SignTransContours;

    // Local control variables 

    HTuple hv_BarWidth = new HTuple(), hv_BarHeight = new HTuple();
    HTuple hv_BarCodeHandle = new HTuple(), hv_InfoModel = new HTuple();
    HTuple hv_SignModel = new HTuple(), hv_InfoRow = new HTuple();
    HTuple hv_InfoColumn = new HTuple(), hv_InfoAngle = new HTuple();
    HTuple hv_InfoScore = new HTuple(), hv_DecodedDataStrings = new HTuple();
    HTuple hv_someitem = new HTuple(), hv_SignRow = new HTuple();
    HTuple hv_SignColumn = new HTuple(), hv_SignAngle = new HTuple();
    HTuple hv_SignScore = new HTuple(), hv_SymbolNames_OCR_01_0 = new HTuple();
    HTuple hv_Ocr_Split = new HTuple(), hv_Area = new HTuple();
    HTuple hv_IDRow = new HTuple(), hv_IDColumn = new HTuple();
    HTuple hv_IDRow1 = new HTuple(), hv_IDColumn1 = new HTuple();
    HTuple hv_IDRow2 = new HTuple(), hv_IDColumn2 = new HTuple();
    HTuple hv_IDHeight = new HTuple(), hv_IDWidth = new HTuple();
    HTuple hv_IDRatio = new HTuple(), hv_HeadSignScale = new HTuple();
    HTuple hv_HeadSignRow = new HTuple(), hv_HeadSignCol = new HTuple();
    HTuple hv_HeadPhi = new HTuple(), hv_sign = new HTuple();
    HTuple hv_BarIndex = new HTuple(), hv_Row = new HTuple();
    HTuple hv_Column = new HTuple(), hv_InfoHomMat2D = new HTuple();
    HTuple hv_SignHomMat2D = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_ImageOut);
    HOperatorSet.GenEmptyObj(out ho_InfoModelContours);
    HOperatorSet.GenEmptyObj(out ho_SignModelContours);
    HOperatorSet.GenEmptyObj(out ho_SymbolRegions);
    HOperatorSet.GenEmptyObj(out ho_ROI_OCR_01_0);
    HOperatorSet.GenEmptyObj(out ho_EDGE);
    HOperatorSet.GenEmptyObj(out ho_ObjectSelected);
    HOperatorSet.GenEmptyObj(out ho_InfoTransContours);
    HOperatorSet.GenEmptyObj(out ho_SignTransContours);
    ho_ImageOut.Dispose();
    ho_ImageOut = new HObject(ho_Image);
    //***
    //** INIT
    //* INIT CONST
    hv_BarWidth.Dispose();
    hv_BarWidth = 800;
    hv_BarHeight.Dispose();
    hv_BarHeight = 100;
    //* INIT IMAGE

    //* INIT BARCODE
    hv_BarCodeHandle.Dispose();
    HOperatorSet.CreateBarCodeModel(new HTuple(), new HTuple(), out hv_BarCodeHandle);
    HOperatorSet.SetBarCodeParam(hv_BarCodeHandle, "quiet_zone", "true");
    //* INIT LOC
        
        HOperatorSet.DispObj(ho_ImageOut, rtaHalconWin);
        HOperatorSet.DispObj(ho_ImageOut, hv_ExpDefaultWinHandle);

        //dump_window_image(ImageResult, WindowHandle);
        
        //stop ()

    ho_ImageOut.Dispose();
    ho_InfoModelContours.Dispose();
    ho_SignModelContours.Dispose();
    ho_SymbolRegions.Dispose();
    ho_ROI_OCR_01_0.Dispose();
    ho_EDGE.Dispose();
    ho_ObjectSelected.Dispose();
    ho_InfoTransContours.Dispose();
    ho_SignTransContours.Dispose();

    hv_BarWidth.Dispose();
    hv_BarHeight.Dispose();
    hv_BarCodeHandle.Dispose();
    hv_InfoModel.Dispose();
    hv_SignModel.Dispose();
    hv_InfoRow.Dispose();
    hv_InfoColumn.Dispose();
    hv_InfoAngle.Dispose();
    hv_InfoScore.Dispose();
    hv_DecodedDataStrings.Dispose();
    hv_someitem.Dispose();
    hv_SignRow.Dispose();
    hv_SignColumn.Dispose();
    hv_SignAngle.Dispose();
    hv_SignScore.Dispose();
    hv_SymbolNames_OCR_01_0.Dispose();
    hv_Ocr_Split.Dispose();
    hv_Area.Dispose();
    hv_IDRow.Dispose();
    hv_IDColumn.Dispose();
    hv_IDRow1.Dispose();
    hv_IDColumn1.Dispose();
    hv_IDRow2.Dispose();
    hv_IDColumn2.Dispose();
    hv_IDHeight.Dispose();
    hv_IDWidth.Dispose();
    hv_IDRatio.Dispose();
    hv_HeadSignScale.Dispose();
    hv_HeadSignRow.Dispose();
    hv_HeadSignCol.Dispose();
    hv_HeadPhi.Dispose();
    hv_sign.Dispose();
    hv_BarIndex.Dispose();
    hv_Row.Dispose();
    hv_Column.Dispose();
    hv_InfoHomMat2D.Dispose();
    hv_SignHomMat2D.Dispose();

    return;
  }
}
